[files]
extend-exclude = [
    ".git/",
    "data/*.json",
    "Ruddarr/Preview Content/*.json",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "[0-9A-F]{24}",
    '"fre"',
    '"mis"',
]

[default.extend-words]

[default.extend-identifiers]
"BroadcasTheNet" = "BroadcasTheNet"
"Github" = "GitHub"
"IDESkipPackagePluginFingerprintValidatation" = "IDESkipPackagePluginFingerprintValidatation"
